stages:   
  - build
  - setup
  - deploy
  - cleanup

build Image and Push to ACR:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$ACR_LOGIN_SERVER\":{\"username\":\"$ACR_USERNAME\",\"password\":\"$ACR_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context . --destination $ACR_REPO:$CI_JOB_ID  


Prequisites:
  stage: setup
  image: mcr.microsoft.com/azure-cli
  before_script:
    -  cd cubejs-manifests
  script:
    # Install kubectl
    - az aks install-cli

    # Authenticate with AKS cluster
    - az login --service-principal -u $AZURE_SP_APP_ID -p $AZURE_SP_PASSWORD  --tenant $TENANT_ID
    - subscriptionId="$(az account list --query "[?isDefault].id" -o tsv)"
    - echo $subscriptionId
    - az account set --subscription $subscriptionId
    # - az aks get-credentials --resource-group Gitlab --name $AKS_CLUSTER_NAME
    - az aks get-credentials --resource-group $RESOURCE_GROUP_NAME --name $CLUSTER_NAME

    # Installing Ingress Controller
    - az aks update -n $CLUSTER_NAME -g $RESOURCE_GROUP_NAME  --enable-disk-driver --enable-file-driver --enable-blob-driver -y
    - chmod 700 get_helm.sh
    - ./get_helm.sh
    - kubectl create namespace ingress-basic
    - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    -  helm repo update
    - helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-basic \--set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz


deploy:
  stage: deploy
  image: mcr.microsoft.com/azure-cli
  script:
    # Install kubectl
    - cd cubejs-manifests
    - sed -i "s/replaceImageTag/${CI_JOB_ID}/g" *
    - ls -al
    - az aks install-cli

    # Authenticate with AKS cluster
    - az login --service-principal -u $AZURE_SP_APP_ID -p $AZURE_SP_PASSWORD  --tenant $TENANT_ID
    - subscriptionId="$(az account list --query "[?isDefault].id" -o tsv)"
    - echo $subscriptionId
    - az account set --subscription $subscriptionId
    # - az aks get-credentials --resource-group Gitlab --name $AKS_CLUSTER_NAME
    - az aks get-credentials --resource-group $RESOURCE_GROUP_NAME --name $CLUSTER_NAME
    - ls -al

    # Deploy to AKS cluster using kubectl
    - kubectl apply -f .
    
Cleanup:
  when: manual
  stage: cleanup
  image: mcr.microsoft.com/azure-cli
  script:
    # Install kubectl
    - cd cubejs-manifests
    - az aks install-cli

    # Authenticate with AKS cluster
    - az login --service-principal -u $AZURE_SP_APP_ID -p $AZURE_SP_PASSWORD  --tenant $TENANT_ID
    - subscriptionId="$(az account list --query "[?isDefault].id" -o tsv)"
    - echo $subscriptionId
    - az account set --subscription $subscriptionId
    # - az aks get-credentials --resource-group Gitlab --name $AKS_CLUSTER_NAME
    - az aks get-credentials --resource-group $RESOURCE_GROUP_NAME --name $CLUSTER_NAME
    - ls -al

    # Deploy to AKS cluster using kubectl
    - kubectl delete -f .
    - kubectl delete namespace ingress-basic