image: 'abhishekf5/maven-abhishek-docker-agent:v1'

variables:
  SONAR_HOST_URL: http://172.171.252.59:9000
  SONAR_LOGIN: 079b8cb6de38d466123f86069aae197478bc617a

# Define the default working directory for the pipeline
before_script:
  - cd java-maven-sonar-argocd-helm-k8s/spring-boot-app

stages:   
  - build
  - test
  - sonarqube
  - dockerization
  - deploy
  - cleanup

build-job:  
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn clean package

unit-test-job:  
  stage: test  
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - mvn test

code-quality-job:  
  stage: sonarqube 
  script:
    - echo "scanning code"
    -  mvn sonar:sonar -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${SONAR_LOGIN}

kaniko:
  stage: dockerization
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]


  script:
    - echo "{\"auths\":{\"cdexgitlab.azurecr.io\":{\"username\":\"cdexgitlab\",\"password\":\"fm0cc8BkqO7Q7da/nSNcRNGkVTahAliel3JbjlIfne+ACRC37O/8\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context java-maven-sonar-argocd-helm-k8s/spring-boot-app/ --destination cdexgitlab.azurecr.io/gitlab-test:$CI_JOB_ID


deploy:
  stage: deploy
  image: mcr.microsoft.com/azure-cli
  script:
    # Install kubectl
    - cd ../spring-boot-app-manifests/
    - sed -i "s/replaceImageTag/${CI_JOB_ID}/g" deployment.yml
    - ls -al
    - az aks install-cli

    # Authenticate with AKS cluster
    - az login --service-principal -u 5c023096-5c14-43b1-acae-f0f22f115f56 -p grY8Q~PDZ71PaveGw448ZbKhGzCHvja4x~Jtla5E --tenant a787b852-29bf-4164-add5-7d55cac58f45
    - subscriptionId="$(az account list --query "[?isDefault].id" -o tsv)"
    - echo $subscriptionId
    - az account set --subscription 0db1b169-34da-432c-98d4-2db3188443a7
    # - az aks get-credentials --resource-group Gitlab --name $AKS_CLUSTER_NAME
    - az aks get-credentials --resource-group Test --name Gitlab
    - ls -al

    # Deploy to AKS cluster using kubectl
    - kubectl apply -f .
    
Cleanup:
  when: manual
  stage: cleanup
  image: mcr.microsoft.com/azure-cli
  script:
    # Install kubectl
    - cd ../spring-boot-app-manifests/
    - az aks install-cli

    # Authenticate with AKS cluster
    - az login --service-principal -u 5c023096-5c14-43b1-acae-f0f22f115f56 -p grY8Q~PDZ71PaveGw448ZbKhGzCHvja4x~Jtla5E --tenant a787b852-29bf-4164-add5-7d55cac58f45
    - subscriptionId="$(az account list --query "[?isDefault].id" -o tsv)"
    - echo $subscriptionId
    - az account set --subscription 0db1b169-34da-432c-98d4-2db3188443a7
    # - az aks get-credentials --resource-group Gitlab --name $AKS_CLUSTER_NAME
    - az aks get-credentials --resource-group Test --name Gitlab
    - ls -al

    # Deploy to AKS cluster using kubectl
    - kubectl delete -f .